/**
 * findEstimatedPrices.js
 *
 * READ-ONLY diagnostic script — does NOT modify any data.
 *
 * Scans all components in MongoDB and flags price entries that appear to
 * be estimated/generated (not from a real product scrape).
 *
 * Detection heuristics:
 *   1. productUrl is a search-page URL (contains ?s=, &search=, route=product%2Fsearch, /s?k=)
 *      — generated by the old generateMultiStoreOffers() urlPattern functions.
 *   2. storeName is "Amazon India" or "Amazon" (no scraper exists).
 *
 * Usage:
 *   cd server
 *   node src/scripts/findEstimatedPrices.js
 *
 *   # To write results to a file:
 *   node src/scripts/findEstimatedPrices.js > estimated_prices_report.txt
 */

import dotenv from 'dotenv';
import mongoose from 'mongoose';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

import Component from '../models/Component.js';

// Patterns that indicate a search-page URL rather than a real product page.
const SEARCH_URL_PATTERNS = [
  /[?&]s=/i,                       // PCStudio, PrimeABGB WooCommerce search
  /[?&]search=/i,                  // Vedant, MDComputers OpenCart search
  /route=product(%2F|\/)?search/i, // MDComputers OpenCart route
  /\/s\?k=/i,                      // Amazon search
];

const FAKE_STORE_NAMES = ['amazon india', 'amazon'];

function looksEstimated(priceEntry) {
  const url = String(priceEntry.productUrl ?? '').trim();
  const store = String(priceEntry.storeName ?? priceEntry.store ?? '').trim().toLowerCase();

  // Check for fake store name
  if (FAKE_STORE_NAMES.includes(store)) {
    return { estimated: true, reason: `Store "${store}" has no working scraper` };
  }

  // Check for search-page URL
  for (const pattern of SEARCH_URL_PATTERNS) {
    if (pattern.test(url)) {
      return { estimated: true, reason: `URL is a search page: ${url.substring(0, 80)}...` };
    }
  }

  return { estimated: false, reason: null };
}

async function main() {
  console.log('\n======================================================');
  console.log('  PCForge — Find Estimated / Fake Price Entries');
  console.log('  (READ-ONLY — no data will be modified)');
  console.log('======================================================\n');

  const uri = process.env.MONGODB_URI || 'mongodb://localhost:27017/pcforge';
  console.log(`-> Connecting to MongoDB at ${uri}...`);
  await mongoose.connect(uri, { useNewUrlParser: true, useUnifiedTopology: true });
  console.log('  OK Connected!\n');

  const cursor = Component.find().select('name category prices').cursor();

  let totalComponents = 0;
  let componentsWithEstimates = 0;
  let totalEstimatedEntries = 0;
  const summary = []; // { componentName, category, estimatedCount, stores[] }

  for (let doc = await cursor.next(); doc != null; doc = await cursor.next()) {
    totalComponents++;
    const estimatedEntries = [];

    for (const entry of (doc.prices || [])) {
      const check = looksEstimated(entry);
      if (check.estimated) {
        estimatedEntries.push({
          store: entry.storeName || entry.store,
          price: entry.price ?? entry.currentPrice,
          url: entry.productUrl,
          reason: check.reason,
        });
      }
    }

    if (estimatedEntries.length > 0) {
      componentsWithEstimates++;
      totalEstimatedEntries += estimatedEntries.length;
      summary.push({
        name: doc.name,
        category: doc.category,
        id: doc._id.toString(),
        estimated: estimatedEntries,
      });

      // Print details for first 20 affected components
      if (componentsWithEstimates <= 20) {
        console.log(`  [!] ${doc.category} | ${doc.name.substring(0, 50)}`);
        for (const e of estimatedEntries) {
          console.log(`      └─ ${e.store}: ₹${e.price} — ${e.reason}`);
        }
      }
    }
  }

  if (componentsWithEstimates > 20) {
    console.log(`  ... and ${componentsWithEstimates - 20} more components with estimated entries.\n`);
  }

  console.log('\n======================================================');
  console.log('  Summary');
  console.log('======================================================');
  console.log(`  Total components scanned:       ${totalComponents}`);
  console.log(`  Components with estimated data: ${componentsWithEstimates}`);
  console.log(`  Total estimated price entries:  ${totalEstimatedEntries}`);
  console.log('======================================================\n');

  if (totalEstimatedEntries > 0) {
    console.log('  To clean these up, you can remove the estimated entries');
    console.log('  from each component\'s prices[] array in MongoDB.');
    console.log('  The affected component IDs are listed above.\n');
  } else {
    console.log('  ✓ No estimated prices found — database is clean!\n');
  }

  await mongoose.disconnect();
  process.exit(0);
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
